### Pagina principal
GET http://localhost:3000/


### Lista todo el contenido
GET http://localhost:3000/contenido


### mostrar una pelicula por ID
GET http://localhost:3000/contenido/2


### filtrar por titulo
GET http://localhost:3000/contenido/title/Friends

